### ISSUE TITLE
[porter/aks] bundle fails with output state required error

### ISSUE THREAD

**Issue by squillace** [Azure/azure-cnab-quickstarts#27]
## Expected Behavior
bundle deploys

## Actual Behavior

╭─ralph at surfacebook in ~ using
╰─○ az container logs -g winlin -n cg-tgsefsf76xk7g --container-name cn-tgsefsf76xk7g
2019/12/12 15:23:39 /usr/local/bin/porter install aks -d azure --tag cnabquickstarts.azurecr.io/porter/aks/bundle:latest --cred /tmp/cnabarmdriver822256693/aks.yaml --param node_count=4 --param azure_location=eastus --param vm_set_type=VirtualMachineScaleSets --param cluster_name=quickstarts --param node_vm_size=Standard_D8s_v3 --param kubernetes_version=1.14.7 --param resource_group=winlin
installing aks...
expath:/usr/local/bin
Running install action on aks
Error: Running install action on aks Error:Bundle has outputs no volume mounted for state, set CNAB_AZURE_STATE_* variables so that state can be retrieved
Error: failed to install the bundle: Command driver (azure) failed executing bundle: exit status 1
2019/12/12 15:23:41 porter command failed with exit status 1

## Steps to Reproduce the Problem

  1. Click the Simple Deploy button
  2. Profit

**Comment by MikeLarah** [comment]
This was due to a couple of issues in the CNAB.ARM-Converter tool:
1. The generated ARM templates did not include a resource to create the file share used for outputs.
2. The environment variables names related to state storage did not match what the CNAB Azure driver was expecting.

Both these issues have been fixed in the tool so new bundles should generate correct ARM templates, and I've regenerated the ARM templates for the existing bundles in the repo.
