### ISSUE TITLE
[porter/ghost] template deploy fails with InvalidTemplate error

### ISSUE THREAD

**Issue by squillace** [Azure/azure-cnab-quickstarts#32]
## Expected Behavior
Template deploys

## Actual Behavior
```
{
  "telemetryId": "e7330939-30e7-4b66-a65b-0c4fb42ccfcd",
  "bladeInstanceId": "Blade_6d540c15b64b4b05b0e8897170c712c1_0_0",
  "galleryItemId": "Microsoft.Template",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplate",
  "message": "Deployment template language expression evaluation failed: 'Unable to parse language expression '': expected token 'Identifier' and actual 'EndOfData'.'. Please see https://aka.ms/arm-template-expressions for usage details.",
  "additionalInfo": [
    {
      "type": "TemplateViolation",
      "info": {
        "lineNumber": 0,
        "linePosition": 0,
        "path": ""
      }
    }
  ]
}
```

## Steps to Reproduce the Problem

  1. Go to https://github.com/Azure/azure-cnab-quickstarts/tree/master/porter/ghost
  2. Click the Simple Deploy button
  3. leave all options empty, but I typed `cat ~/.kube/config | base64 --wrap=0 | pbcopy` on my own machine to capture the required base64-encoded string without any returns and paste into the kubecon field
  4. Profit

**Comment by MikeLarah** [comment]
This was due to the fact that we had string parameters in the ARM template with value `[]`, which ARM was trying to interpret as an empty expression.

I've updated the converter tool to handle the case for new quickstarts (it adds an extra `[` to escape the open square bracket), and updated the existing quickstarts' ARM templates to comply.
