### ISSUE TITLE
[porter/dapr] won't uninstall

### ISSUE THREAD

**Issue by squillace** [Azure/azure-cnab-quickstarts#42]
## Expected Behavior
Dapr is uninstalled

## Actual Behavior
The following is as far as the uninstallation process can get. The ACI dashboard indicates that the porter container never gets created, so instead of the two-step ACI+ACI work that occurs for the installation -- that is, bootstrap and then running porter -- it just runs the bootstrap and the uninstall never executes... seemingly.

```
020/01/09 17:58:39 /usr/local/bin/porter uninstall dapr -d azure --tag cnabquickstarts.azurecr.io/porter/dapr/bundle:latest --cred /tmp/cnabarmdriver014507301/dapr-creds.yaml --param-file /tmp/cnabarmdriver012496448/dapr-params.txt
uninstalling dapr...
```

## Steps to Reproduce the Problem

  1. Install the https://github.com/Azure/azure-cnab-quickstarts/tree/master/porter/dapr bundle
  2. Click the Deploy From Button a second time, use the same credentials, but then edit the template in the portal to use the `uninstall` action. 
  3. Follow the process to see what happens.

**Comment by squillace** [comment]
Same behavior with Mattermost.

```
2020/01/12 22:14:45 /usr/local/bin/porter uninstall mattermost-team-edition -d azure --tag cnabquickstarts.azurecr.io/porter/mattermost-team-edition/bundle:0.1.0 --cred /tmp/cnabarmdriver678694086/mattermost-team-edition-creds.yaml --param-file /tmp/cnabarmdriver248071021/mattermost-team-edition-params.txt
uninstalling mattermost-team-edition...
```

**Comment by MikeLarah** [comment]
This is now fixed. As we discussed, I've updated the cnabarmdriver so that Porter is now using the azure plugin, and storing the instance info in blob container that we create as part of the ARM deployment. Changes to the driver are in the other repo here https://github.com/endjin/CNAB.ARM-Converter/commit/fcde6cfbe07a0e263bee9f086c08b74c196f6aaa (and following few commits).

I've also updated all the existing ARM templates in the quickstarts in this repo so that they use the latest cnabarmdriver image, and deploy the necessary storage bits (see this commit https://github.com/Azure/azure-cnab-quickstarts/commit/62b6828086a3a19900a5711a14ffdc57f480beaf)

So this now means that upgrade/uninstall actions work when you use 'Deploy from Azure' button across all the quickstarts (so long as you select the same resource group that you selected when running the install).

**Comment by squillace** [comment]
right
Chatted with Carolyn about this a bit, and what's coming down the pike is the ability for a porter plugin to dynamically pick up identity bits prior to launching the invocation image, which would give the driver in azure a way to launch the identity with the token mounted internally and picked up by azure resources automatically, even without needing msi. 

Upside about doing this is that the Porter local installation activity would then work precisely the same way. 

I'll test it out!

**Comment by squillace** [comment]
WORKS! Thanks a ton, @MikeLarah
